spring.application.name=finance-tracker

# MongoDB - values will be injected from EnvConfig
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# Server
server.port=${SERVER_PORT:8080}
server.error.whitelabel.enabled=false
server.error.path=/error

app.maintenance=false

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Session
server.servlet.session.timeout=30d